# Generated by Django 4.1.3 on 2022-11-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-id'], 'verbose_name': 'Colección', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterModelOptions(
            name='payterm',
            options={'ordering': ['-id'], 'verbose_name': 'Termino de pago', 'verbose_name_plural': 'Terminos de pago'},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'ordering': ['-id'], 'verbose_name': 'Orden de venta', 'verbose_name_plural': 'Ordenes de venta'},
        ),
        migrations.AlterModelOptions(
            name='saleorderitem',
            options={'ordering': ['-id'], 'verbose_name': 'Articulo Solicitado', 'verbose_name_plural': 'Articulos Solicitados'},
        ),
    ]
