# Generated by Django 4.1.3 on 2022-11-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='item_code',
            field=models.CharField(default=1, max_length=100, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
