# Generated by Django 4.1.3 on 2022-11-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_reference_item_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['-id'], 'verbose_name': 'Referencia', 'verbose_name_plural': 'Referencias'},
        ),
    ]
