# Generated by Django 4.1.3 on 2022-11-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('dimension', models.CharField(max_length=255, verbose_name='Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('referece', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.reference', verbose_name='referencia')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('last_modification', models.DateTimeField(verbose_name='Última modificación')),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Bruto')),
                ('responsible', models.CharField(max_length=255, verbose_name='Responsable')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='box.dimension', verbose_name='Dimensión')),
            ],
        ),
    ]
