# Generated by Django 4.1.3 on 2022-11-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0003_remove_boxitem_referece_remove_saleorder_collection_and_more'),
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='picking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='picking.picking', verbose_name='Despacho'),
            preserve_default=False,
        ),
    ]
