# Generated by Django 4.1.3 on 2022-11-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_box_picking'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxitem',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='box.box', verbose_name='Caja'),
            preserve_default=False,
        ),
    ]
