# Generated by Django 4.1.3 on 2022-11-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_boxitem_box'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['-last_modification'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='boxitem',
            options={'ordering': ['-id'], 'verbose_name': 'Referencia empacada', 'verbose_name_plural': 'Referencias empacadas'},
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={'ordering': ['id'], 'verbose_name': 'Dimension', 'verbose_name_plural': 'Dimensiones'},
        ),
    ]
