# Generated by Django 4.1.3 on 2022-11-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_alter_box_last_modification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxitem',
            old_name='referece',
            new_name='reference',
        ),
    ]
