# Generated by Django 4.1.3 on 2022-11-18 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('dimension', models.CharField(max_length=255, verbose_name='Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='PayTerm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Referencia')),
                ('model_size', models.CharField(max_length=100, verbose_name='Talla')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPicking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('referece', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picking.reference', verbose_name='referencia')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('no_sale_order', models.CharField(max_length=20, verbose_name='No Orden de venta')),
                ('publication_date', models.DateField(verbose_name='Fecha publicación')),
                ('delivery_date', models.DateField(verbose_name='Fecha de entrega')),
                ('doc_date', models.DateField(verbose_name='Fecha de documento')),
                ('po_comments', models.TextField(verbose_name='PO Comentarios')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Dirección de entrega')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picking.collection', verbose_name='Colección')),
                ('pay_term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picking.payterm', verbose_name='Término de pago')),
            ],
        ),
        migrations.CreateModel(
            name='Picking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('last_modification', models.DateTimeField(verbose_name='Última modificación')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picking.saleorder', verbose_name='Orden de venta')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picking.statuspicking', verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('referece', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picking.reference', verbose_name='referencia')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('last_modification', models.DateTimeField(verbose_name='Última modificación')),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Bruto')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picking.dimension', verbose_name='Dimensión')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
        ),
    ]
