# Generated by Django 4.1.3 on 2022-11-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0001_initial'),
        ('picking', '0002_alter_box_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxitem',
            name='referece',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='pay_term',
        ),
        migrations.RemoveField(
            model_name='saleorderitem',
            name='referece',
        ),
        migrations.AlterField(
            model_name='picking',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleorder.saleorder', verbose_name='Orden de venta'),
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.DeleteModel(
            name='BoxItem',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Dimension',
        ),
        migrations.DeleteModel(
            name='PayTerm',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='SaleOrder',
        ),
        migrations.DeleteModel(
            name='SaleOrderItem',
        ),
    ]
