# Generated by Django 4.1.3 on 2022-11-19 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0003_remove_boxitem_referece_remove_saleorder_collection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picking',
            options={'ordering': ['-id'], 'verbose_name': 'Despacho', 'verbose_name_plural': 'Despachos'},
        ),
        migrations.AlterModelOptions(
            name='statuspicking',
            options={'ordering': ['-id'], 'verbose_name': 'Estado despacho', 'verbose_name_plural': 'Estados despacho'},
        ),
        migrations.AlterField(
            model_name='picking',
            name='last_modification',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última modificación'),
        ),
    ]
