# Generated by Django 4.1.3 on 2022-11-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0004_alter_picking_options_alter_statuspicking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='responsible',
            field=models.CharField(max_length=255, verbose_name='Responsable'),
        ),
    ]
